### ISSUE TITLE
Proxy?

### ISSUE THREAD

**Issue by stephanbuys** [inre/rust-mq#12]
Hi, I'm a n00b at MQTT - does it support http_proxy to allow events to be sent out from inside enterprises?

**Comment by inre** [comment]
Hello,
The MQTT client is working over TCP. it doesn't support WebSockets (through HTTP) in the current version.

**Comment by stephanbuys** [comment]
Is it in the spec, is it something we could possibly add or sponsor to add? I'm looking for a reliable (secure) way to transport events from all sorts of environments.

**Comment by inre** [comment]
Why do you need rust implementation? A lot of languages have the MQTT clients over WebSockets and so on. I have a plan to implement MQTT over WebSockets in future.
