### ISSUE TITLE
Client not receiving messages after broker is down and up again

### ISSUE THREAD

**Issue by tekjar** [inre/rust-mq#4]
Slight modification to subscribe example in mqttc

```
loop {
        match client.await() {
            Ok(result) => {
                match result {
                    Some(message) => println!("{:?}", message),
                    None => println!("."),
                }
            }
            Err(_) => continue,     
        }
    }
```

Start `rust-mq` client

```
RUST_LOG=info,mqttc cargo run --example sub -- 127.0.0.1:1883 a/b/c
```

Keep publishing with `mosquitto_pub`

```
 while true; do sleep 1; mosquitto_pub -t "a/b/c" -m "Hello World"; done
```

Take down the broker and bring it up again. `rust-mq` client won't be receiving publishes anymore

**Comment by inre** [comment]
I fixed this. But it's not whole doing after reconnection. it needs to resend all unacknowledged messages.

**Comment by tekjar** [comment]
Thanks for this library. I just did another test. 

My observations:

Client is not receiving any messages after broker is down (crashed) because all the broker state is gone (persistence not enabled in mosquitto config). I tested client with below config and persitence enabled in broker.

```
opts.set_client_id("xxxxxx");
opts.set_clean_session(false);
```

Now I'm receiving messages again after reconnections.
