### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by kinghajj** [inre/rust-mq#8]
I've noticed that between 0.1.2 and the current master, `ClientOptions` added a `Send` constraint to the incoming/outgoing stores. I need this for a project, so at first I attempted to reference each of `mqttc`/`mqtt3`/`netopts` to this repository, but that seems to cause rustc to re-compile the packages, resulting in "type mismatch" errors when implementing the `Store` trait. There's probably a way around that, but I figure it may just be easier for me and others if a version 0.1.3 is published with the recent changes.

**Comment by inre** [comment]
it's done. Just execute `cargo update`. I'm advising such dependencies in your `Cargo.toml`:

```
[dependencies]
log = "0.3"
env_logger = "0.3"
mqttc = "0.1"
mqtt3 = "0.1"
netopt = "0.1"
```
